# Generated by Django 3.2.10 on 2022-03-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0006_alter_recommendation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon_api.product'),
        ),
    ]
